%\VignetteIndexEntry{Bioconductor LaTeX Style}
%\VignettePackage{BiocStyle}
%\VignetteEngine{knitr::knitr}

\documentclass{article}

<<style, eval=TRUE, echo=FALSE, results='asis'>>=
BiocStyle::latex()
@

\renewcommand{\baselinestretch}{1.25}

\newcommand{\exitem}[3]{%
  \item \texttt{\textbackslash#1\{#2\}} #3 \csname#1\endcsname{#2}.%
}

\bioctitle[powsimR]{powsimR: Power Analysis and Sample Size Estimation for Bulk and Single Cell RNA-Seq Experiments}
\author{Beate Vieth \footnote{vieth@bio.lmu.de}}

\begin{document}

\maketitle

%\packageVersion{\Sexpr{BiocStyle::pkg_ver("powsimR")}}

Report issues on \url{https://github.com/bvieth/powsimR/issues}

\newpage

\tableofcontents

<<setup, include=FALSE, cache=FALSE>>=

knitr::opts_chunk$set(xtable.comment = FALSE,
                      echo=F,
                      eval=F,
                      message = F,
                      warning=F,
                      error = F,
                      cache = F,
                      tidy = T,
                      results='hide',
                      fig.lp='fig:',
                      fig.align = 'center',
                      fig.path='vignette-',
                      tidy.opts=list(width.cutoff=60)
                     )

# set the width of your R code output
options(width=60)

@

\newpage

%---------------------------------------------------------
\section{Installation guide}
%---------------------------------------------------------

PowsimR has a number of dependencies that need to be installed before hand (see also the README file on github). I recommend to increase the maximum number of DLLs that can be loaded to at least 500. The environmental variable R\_MAX\_NUM\_DLLS can be set in R\_HOME/etc/Renviron prior to starting R (for further details see \Rfunction{Startup}).

<<echo=T, eval=F>>=
ipak <- function(pkg, repository=c('CRAN', 'Bioconductor', 'github')){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) {
    if(repository=='CRAN') {
      install.packages(new.pkg, dependencies = TRUE)
    }
    if(repository=='Bioconductor') {
      source("https://bioconductor.org/biocLite.R")
      biocLite(new.pkg, dependencies=TRUE, ask=FALSE)
    }
    if(repository=='github') {
      devtools::install_github(pkg, build_vignettes = FALSE)
    }
  }
}

# CRAN PACKAGES
cranpackages <- c("gamlss.dist", "methods", "stats", "moments", "doParallel", "parallel", "reshape2", "dplyr", "tidyr", "data.table", 'ggplot2', 'ggthemes', 'ggExtra', 'cowplot', 'scales', 'fitdistrplus', 'MASS', 'pscl', 'nonnest2', 'cobs', 'msir', 'drc', 'devtools', 'XML', 'splines')
ipak(cranpackages, repository='CRAN')

# BIOCONDUCTOR
biocpackages <- c('S4Vectors', 'AnnotationDbi', 'Biobase', 'BiocParallel', 'BiocStyle', 'scater', 'scran', 'edgeR', 'limma', 'DESeq2', 'baySeq', 'NOISeq', 'EBSeq', 'DSS', 'MAST', 'ROTS', "IHW", 'qvalue')
ipak(biocpackages, repository='Bioconductor')

# GITHUB
githubpackages <- c('gu-mi/NBGOF', 'hms-dbmi/scde', 'nghiavtr/BPSC')
ipak(githubpackages, repository = 'github')
devtools::install_github('kdkorthauer/scDD', build_vignettes = FALSE, ref = 'develop')
@

%---------------------------------------------------------
\section{Introduction}
%---------------------------------------------------------

In this vignette, we illustrate the features of \Rpackage{powsimR} by assessing the power to detect differential expression between two groups of embryonic stem cells cultured in standard 2i medium (\href{http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-2600/}{E-MTAB-2600}) \cite{Kolodziejczyk2015-vn}.

%---------------------------------------------------------
\section{\Rpackage{powsimR} workflow}
%---------------------------------------------------------

The basic workflow of \Rpackage{powsimR} is illustrated in figure \ref{fig:powsim_scheme}: A) The mean-dispersion relationship is estimated from RNA-seq data, which can be either single cell or bulk data. The users can provide their own count tables or one of our five example data sets. B) These distribution parameters are then used to set-up the simulations. For better comparability, the parameters for the simulation of differential expression are set separately. C) Finally, the TPR and FDR are calculated. Both can be either returned as marginal estimates per sample configuration (shown), or stratified according to the estimates of mean expression, dispersion or dropout-rate .

\begin{figure}[h]
\centering
\includegraphics[width=0.9\linewidth]{powsim_schematic.jpeg}
\caption{\textbf{PowsimR schematic overview.} (A) Estimation: (B) Simulation: (C) Evaluation. Functions given in orange.}
\label{fig:powsim_scheme}
\end{figure}

\section{Parameter estimation}

The parameters of the negative binomial distribution, i.e. mean and dispersion are estimated by the function \Rfunction{estimateNBParam}. In addition, the dropout probability, i.e. the fraction of zero counts per gene, is calculated.
The user can choose between three estimation frameworks:
\begin{description}
\item[edgeR] \Biocpkg{edgeR} \cite{Robinson2010-ni}.
\item[DESeq2] \Biocpkg{DESeq2} \cite{Love2014-je}.
\item[MatchMoments] Matching moments estimation of mean and dispersion based on normalized counts.
\end{description}

As described in edgeR and DESeq2, their frameworks are able to handle experimental setup information. For example, the user can specify batches and other characteristics of the samples.

The library size normalisation methods are trimmed mean of M-values for edgeR and median-of-ratios method for DESeq2 and MatchMoments for bulk RNA-seq data. For single cell RNA-seq data, the deconvolution method \Rfunction{computeSumFactors} in \Biocpkg{scran} is used \cite{Lun2016-ep}.

The estimates, sequencing depth and normalisation factors are plotted with \Rfunction{plotNBParam}.

With the following command, we estimate and plot the parameters for the embryonic stem cells cultured in standard 2i+lif medium (Kolodziejczyk) (figure \ref{fig:NBparams}). As expected for single cell RNA-seq, the variability (i.e. dispersion) and dropout rates are high. Furthermore, the dispersion strongly depends on the mean and does not level off with higher mean values.

<<echo=TRUE,eval=FALSE>>=
# download count table
githubURL <- "https://github.com/bvieth/powsimRData/raw/master/data-raw/kolodziejczk_cnts.rda"
download.file(url = githubURL, destfile= "kolodziejczk_cnts.rda", method = "wget")
load('kolodziejczk_cnts.rda')
kolodziejczk_cnts <- kolodziejczk_cnts[, grep('standard', colnames(kolodziejczk_cnts))]

TwoiLIF.params = estimateNBParam(countData = kolodziejczk_cnts,
                               cData = NULL,
                               design = NULL,
                               RNAseq = 'singlecell',
                               estFramework = 'MatchMoments',
                               sigma= 1.96)
plotNBParam(TwoiLIF.params)
@

We have implemented a read count simulation framework assuming an underlying negative binomial distribution.
To predict the dispersion given a random draw of mean expression value observed, we apply a locally weighted polynomial regression fit. To capture the variability of dispersion estimates observed, a local variability prediction band is applied.
For bulk RNA-seq experiments, dropouts are less probable but can still occur. To include this phenomenon we sample from the observed dropout rates for genes that have a mean expression value below 5\% dropout probability determined by a decrease constrained B-splines regresssion of dropout rate against mean expression (\Rfunction{cobs} in \CRANpkg{cobs}).
The resulting read count matrix has similar distributional characteristics as the original Kolodziejczyk data set (figure \ref{fig:simeval}).

\begin{figure}[h]
\centering
\includegraphics[width=0.75\linewidth]{NBparams.jpeg}
\caption{\textbf{Estimated parameters for Kolodziejczyk data set.} A) Sequencing depth per sample with median sequencing depth (grey dashed line). B) Library size normalisation factor per sample with median size factor (grey dashed line). C) Local polynomial regression fit between mean and dispersion estimates with variability band per gene (yellow). Common dispersion estimate (grey dashed line). D) Fraction of dropouts versus estimated mean expression per gene.}
\label{fig:NBparams}
\end{figure}

\begin{figure}[h]
\centering
\includegraphics[width=0.7\linewidth]{simeval.jpeg}
\caption{\textbf{Comparison of estimated and simulated read counts} (A) Dispersion versus Mean. (B) Dropout versus Mean.}
\label{fig:simeval}
\end{figure}

%---------------------------------------------------------
\section{Simulations}
%---------------------------------------------------------
For simulating differential expression between two groups, the number of genes, number of simulations, percentage of differential expression and effect size are set up with the function \Rfunction{DESetup}. The effect size is here defined as the log2 fold change which can be a constant, sampled from a vector or function. The uniform, normal and gamma distributions are possible options and illustrated in figure \ref{fig:lfcs}. Depending on the settings, these distribution can be broader or narrower. If using this option, we recommend to choose a distribution that closely resembles previously observed or expected fold changes.

The distribution estimates and these settings are then combined to one object with \Rfunction{SimSetup}. This allows the user to assess power of multiple groupwise comparisons and different differential testing methods.
The following command sets up simulations with 10,000 genes, 20\% genes being DE, log fold change sample from a narrow gamma distribution and parameter estimates based on Kolodziejczyk data:

<<echo=TRUE,eval=FALSE>>=

lfc.gamma = function(x) sample(c(-1,1), size=x,replace=T)*rgamma(x, 3, 3)
de.opts = DESetup(ngenes=10000, nsims=25, p.DE=0.2, LFC=lfc.gamma)
sim.opts = SimSetup(desetup = de.opts, params = TwoiLIF.params, size.factors='given')
@

With the setup defined, the differential expression simulation is run with \Rfunction{simulateDE}. For this, the user needs to set the following options:

\begin{description}
  \item[Replicates] The number of sample replicates per group (n1 and n2). These can be unbalanced.
  \item[DEmethod] The differential testing method. The user can choose between 12 methods in total.  8 developed for bulk, 4 developed for single cells.
  \item[ncores] A number of DE methods are able to run in parallel too speed up differential testing.
\end{description}

<<echo=TRUE,eval=FALSE>>=
simDE = simulateDE(n1 = c(24,48,96,192,384,800),
                   n2 = c(24,48,96,192,384,800),
                   sim.settings = sim.opts,
                   ncores = 10,
                   DEmethod = 'MAST',
                   verbose = T)

@

\begin{figure}[h]
\centering
\includegraphics[width=0.6\linewidth]{lfcdist.jpeg}
\caption{Log2 fold change examples for gamma, uniform and normal distribution}
\label{fig:lfcs}
\end{figure}

\section{Evaluation}

The results of differential expression simulation are evaluated with \Rfunction{evaluateSim}. We have separated the evaluation from DE detection to allow the user to evaluate power in a comprehensive way as advocated by \cite{Wu2015-uj}.
In this function, the proporations and error rates are estimated. The rates can be stratified by mean, dispersion or dropout. Furthermore, the user can choose between different multiple testing correction methods (see \Rfunction{p.adjust.methods}, \Rfunction{ihw} in \Biocpkg{IHW} and \Rfunction{qvalue} in \Biocpkg{qvalue}). Also, the genes can be filtered by mean, dispersion or dropout. To define biologically interesting genes, a cutoff for the log2 fold change with delta can be set.

With the following command we evaluate the marginal TPR and TPR conditional on the mean expression for the simulation based on Kolodziejczyk data.

<<echo=TRUE,eval=FALSE>>=
evalDE = evaluateSim(simRes = simDE,
                     alpha.type = 'adjusted',
                     MTC = 'BH',
                     alpha.nominal = 0.1,
                     stratify.by = 'mean',
                     filter.by = 'none',
                     strata.filtered = 0,
                     target.by = 'lfc',
                     delta = 0)
@

The results of the evaluation can be plotted with \Rfunction{plotEvalRes}.
\begin{description}
  \item[rate] Marginal or Conditional Error Rates calculations. The conditional error rates are determined and calculated with \Rfunction{evaluateSim}. The number of genes per stratum are also summarised.
  \item[quick] If this is set to \R{TRUE} then only the TPR and FDR will be plotted.
\end{description}

With the following commands, the quick marginal and conditional power assessment for the Kolodziejczyk data is plotted.

<<echo=TRUE,eval=FALSE>>=
plotEvalRes(evalRes = evalDE,
            rate='marginal',
            quick=TRUE, annot=TRUE)

plotEvalRes(evalRes = evalDE,
            rate='stratified',
            quick=TRUE, annot=TRUE)
@

%---------------------------------------------------------
\section{Additional Functionalities}
%---------------------------------------------------------

\subsection{Evaluate Simulation Framework}

It is important to validate the appropiateness of the chosen simulation framework. The function \Rfunction{evaluateDist} compares the theoretical fit of the poisson, negative binomial, zero-inflated poisson and zero-inflated negative binomial and Beta-Poisson distribution to the empirical RNA-seq read counts (\cite{Colin_Cameron2013-vb}, \cite{Kim2013-qo}, \cite{Delmans2016-ef}).
The evaluation is then summarized with the function \Rfunction{summariseDist} which chooses the best fitting distribution per gene based on goodness-of-fit statistics (Chi-square test), Akaike Information Criterium and comparing observed dropouts with zero count prediction of the models.
% As noted by other developers, goodness-of-fit tests are not an objective tool and heavily depend on sample sizes (\cite{Delignette-Muller2015-ie}). A graphical evaluation of the fitted distribution is considered the most appropiate way but for high-throughput sequencing an unrealistic recommendation.
Bulk RNA-seq experiments are usually conducted with a small number of samples. We therefore recommend to rely on the goodness-of-fit validation by \cite{Mi2015-ri}. To use this approach in \Rfunction{evaluateDist}, the user should allow for permutation simulations by setting the value of nsims to at least 100. If available, the computation can be run on multiple cores by setting the number of cores (ncores).

With the following command, we estimate and plot the parameters for the embryonic stem cells cultured in standard 2i lif medium (Kolodziejczyk).

<<echo=TRUE,eval=FALSE>>=
TwoiLIF.distfit = evaluateDist(cnts = kolodziejczk_cnts,
                             RNAseq = 'singlecell',
                             ncores = 1,
                             nsims = 1,
                             frac.genes = 1,
                             min.meancount = 1,
                             min.libsize =1000)

plotEvalDist(evalDist = TwoiLIF.distfit, annot=F)
@

\begin{figure}[h]
\centering
\includegraphics[width=0.75\linewidth]{evaldist.pdf}
\caption{A) Goodness-of-fit of the model per gene assessed with a chi-square test based on residual deviance and degrees of freedom. B) Akaike Information Criterion per gene: Model with the lowest AIC (red). Model with the lowest AIC and passed goodness-of-fit statistic test (teal). C) Observed versus predicted dropouts per model and gene. D) Model assessment per gene based on likelihood ratio test for nested models and Vuong test for non-nested models.}
\label{fig:evaldist}
\end{figure}

\subsection{Negative Binomial Parameters}

\subsubsection{in silico Parameter Definition}

We have also implemented the option to approximate the read count matrix simulation based on random distribution functions in \R{}. The user then has to define the mean, dispersion, dropout and library size in \Rfunction{insilicoNBParam}. In the absence of suitable pilot studies, a typical single cell RNA-seq experiment could be approximated with:
\begin{itemize}
  \item mean: \Rcode{function(x) rgamma(x, 4, 2)} where x is the number of genes
  \item dispersion: \Rcode{function(x) 2 + 100/x} where x is the mean
  \item library size: \Rcode{function(x) 2**rnorm(n=x, mean=0, sd=0.25)} where x is the number of samples
\end{itemize}

The same functionality can also be used for bulk RNA-seq.

\subsubsection{Count matrices of single cell RNA-seq experiments}

We have uploaded read count matrices of 5 single cell RNA-seq experiments on \href{https://github.com/bvieth/powsimRData}{github}.
The user can calculate the negative binomial parameters with \Rfunction{estimateNBParam}, view these estimates with \Rfunction{plotNBParam} and use it as an input for \Rfunction{SimSetup}.

\subsubsection{Access to raw read counts stored in online data base}

We have provided a number of exemplatory single cell RNA-seq data sets for parameter estimation. Nevertheless, you might not find a data set that matches your own experimental setup. In those cases, we recommend to check online repositories for a suitable data set. Below you can find an example script to get count tables from recount (\url{https://jhubiostatistics.shinyapps.io/recount/}) \cite{Collado-Torres2017-mo}. For a single cell RNA-seq data base, see conquer and its tutorial (\url{http://imlspenticton.uzh.ch:3838/conquer/}).
As before, the user can then calculate the negative binomial parameters with \Rfunction{estimateNBParam}, view these estimates with \Rfunction{plotNBParam} and use it as an input for \Rfunction{SimSetup}.

<<online_repos, echo=T, eval=F>>=
# Install and load the R package
source('http://bioconductor.org/biocLite.R')
biocLite('recount')
library('recount')

# Download the data set
url <- download_study('SRP060416')

# Load the data
load(file.path('SRP060416', 'rse_gene.Rdata'))

# count table
cnts <- assay(rse_gene)
# sample annotation
sample.info <- data.frame(colData(rse_gene)@listData, stringsAsFactors=F)
# gene annotation
gene.info <- data.frame(GeneID=rowData(rse_gene)@listData$gene_id, GeneLength=rowData(rse_gene)@listData$bp_length, stringsAsFactors=F)
@


\subsection{Simulation settings}

By default, there is no difference in library sizes between the samples. If the user wishes for a more realistic, i.e. more variable distribution of read counts across samples, the library sizes can be sampled from observed, vector or function.

%---------------------------------------------------------
\section{Wrapper Function}
%---------------------------------------------------------

\Rfunction{PowSim} is a wrapper including estimation, simulation and evaluation. Please consult the detailed description of \Rfunction{PowSim} help page for more information.
<<echo=T, eval=F>>=
res <- PowSim(input=NULL, RNAseq='singlecell', ngenes=10000, nsims=25, p.DE=0.1, LFC=function(x) sample(c(-1,1), size=x,replace=T)*rgamma(x, 3, 3), size.factors='equal', ncores=10, DEmethod="MAST", save.plots=TRUE, verbose=TRUE)
@


%---------------------------------------------------------
\section{Session info}
%---------------------------------------------------------

Here is the output of \Rfunction{sessionInfo} on the system on which
this document was compiled:
<<sessionInfo, results='asis', echo=FALSE, eval=TRUE>>=
toLatex(sessionInfo())
@

\bibliography{Bioc}

\end{document}
