# Authors@R: person("Beate", "Vieth", role = c("aut", "cre"), email = "vieth.beate@gmail.com", comment = c(ORCID = "0000-0002-8415-1695"))

write.dcf(list(
  Package = "powsimR",
  Type = "Package",
  Title = "Power Simulations for RNA-sequencing",
  Description = "Recent development of very sensitive RNA-seq protocols, such as Smart-seq2 and CEL-seq allows transcriptional profiling at single-cell resolution and droplet devices make single cell transcriptomics high-throughput, allowing to characterize thousands or even millions of single cells. In powsimR, we have implemented a flexible tool to assess power and sample size requirements for differential expression (DE) analysis of single cell and bulk RNA-seq experiments. For our read count simulations, we (1) reliably model the mean, dispersion and dropout distributions as well as the relationship between those factors from the data. (2) Simulate read counts from the empirical mean-variance and dropout relations, while offering flexible choices of the number of differentially expressed genes, effect sizes and DE testing method. (3) Finally, we evaluate the power over various sample sizes. The number of replicates required to achieve the desired statistical power is mainly determined by technical noise and biological variability and both are considerably larger if the biological replicates are single cells. powsimR can not only estimate sample sizes necessary to achieve a certain power, but also informs about the power to detect DE in a data set at hand. We believe that this type of posterior analysis will become more and more important, if results from different studies are to be compared. Often enough researchers are left to wonder why there is a lack of overlap in DE-genes across similar experiments. PowsimR will allow the researcher to distinguish between actual discrepancies and incongruities due to lack of power.",
    Version = "0.0.900",
  Imports = "BiocParallel,
             broom,
             cobs,
             cowplot,
             data.table,
             DESeq2,
             doParallel,
             dplyr,
             edgeR,
             fitdistrplus,
             ggplot2,
             ggpubr,
             ggstance,
             grDevices,
             grid,
             Hmisc,
             iCOBRA,
             IHW,
             limma,
             magrittr,
             MASS,
             matrixStats,
             methods,
             minpack.lm,
             moments,
             msir,
             nonnest2,
             plotrix,
             plyr,
             pscl,
             qvalue,
             reshape2,
             rlang,
             SAVER,
             scales,
             scran,
             scuttle,
             SingleCellExperiment,
             stats,
             SummarizedExperiment,
             tibble,
             tidyr,
             truncnorm,
             utils,
             zoo",
  Remotes = "bioc::BiocParallel,
             bioc::DESeq2,
             bioc::edgeR,
             bioc::iCOBRA,
             bioc::IHW,
             bioc::limma,
             bioc::qvalue,
             bioc::scran,
             bioc::scuttle,
             bioc::SingleCellExperiment,
             bioc::SummarizedExperiment",
  Depends = "R (>= 4.0), gamlss.dist",
    Suggests = "BiocStyle,
                knitr,
                rmdformats,
                mvtnorm,
                MBESS",
    LazyData = TRUE,
    Encoding = "UTF-8",
    VignetteBuilder = 'knitr',
    License = "GPL",
    NeedsCompilation = "no",
    Author = "Beate Vieth",
    Date = paste(Sys.Date()),
    BugReports = "https://github.com/bvieth/powsimR/issues",
    URL = "https://github.com/bvieth/powsimR",
    Maintainer = "Beate Vieth <vieth.beate@gmail.com>"),
    file = "DESCRIPTION")
