write.dcf(list(Package = "powsimR",
               Type="Package",
               Title = "Power Simulations for RNA-sequencing",
               Description = "This package provides simulation based methods for evaluating the statistical power to detect differential expression in bulk and single cell RNA-seq experiments",
               Version = "1.0.0",
               Imports = "methods,
                          stats,
                          matrixStats,
                          moments,
                          S4Vectors,
                          gtools,
                          AnnotationDbi,
                          Biobase,
                          BiocGenerics,
                          SummarizedExperiment,
                          BiocParallel,
                          doParallel,
                          parallel,
                          snow,
                          reshape2,
                          dplyr,
                          tidyr,
                          data.table,
                          ggplot2,
                          ggthemes,
                          ggExtra,
                          cowplot,
                          scales,
                          fitdistrplus,
                          NBGOF,
                          MASS,
                          pscl,
                          nonnest2,
                          cobs,
                          msir,
                          drc,
                          RUVSeq,
                          scran,
                          scater,
                          SCnorm,
                          edgeR,
                          limma,
                          DESeq2,
                          baySeq,
                          NOISeq,
                          NBPSeq,
                          EBSeq,
                          DSS,
                          BASiCS,
                          MAST,
                          scde,
                          scDD,
                          ROTS,
                          BPSC,
                          monocle,
                          VGAM,
                          IHW,
                          qvalue",
               Remotes = "gu-mi/NBGOF,
                          hms-dbmi/scde,
                          nghiavtr/BPSC,
                          catavallejos/BASiCS,
                          rhondabacher/SCnorm",
               Depends = "R (>= 3.4),
                          gamlss.dist,
                          splines",
               Suggests = "BiocStyle,
                           knitr",
               VignetteBuilder = 'knitr',
               License = "GPL",
               NeedsCompilation = "no",
               Author = "Beate Vieth",
               Date = paste(Sys.Date()),
               Maintainer = "Beate Vieth <vieth.beate@gmail.com>"),
               file = "DESCRIPTION")


